import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./nextauthProvider";
import { ApolloProvider } from '@apollo/client'
import { ApolloWrapper } from "./apolloConfig/apolloClientWrapper";
import client from "./apolloConfig/apolloClient"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}><ApolloWrapper><NextAuthProvider>{children}</NextAuthProvider></ApolloWrapper></body>
    </html>
  );
}
